version: '3.8'

services:
  etl:
    build: .
    command: python main.py
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DATABASE_URL=postgresql://adarsh:zxcvbnm@db:5432/etl_db
      - FILE_PATH=/app/employee_details.csv
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: etl_db
      POSTGRES_USER: adarsh
      POSTGRES_PASSWORD: zxcvbnm
    ports:
      - "5432:5432"

  test:
    build: .
    command: python -m unittest tests.py
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DATABASE_URL=postgresql://adarsh:zxcvbnm@db:5432/etl_db
      - FILE_PATH=/app/employee_details.csv
    depends_on:
      - db
